const sampleCourses = [
  {
    id: 1,
    title: 'React for Beginners',
    description: 'Learn the basics of React and build dynamic web apps.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Day',
    availability: 'Available Now',
    recommended: true,
  },
  {
    id: 2,
    title: 'Advanced CSS Techniques',
    description: 'Master CSS for modern responsive design.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Days',
    availability: 'Available Now',
    topRated: true,
  },
  {
    id: 3,
    title: 'Digital Marketing 101',
    description: 'Introduction to digital marketing strategies.',
    thumbnail: 'assets/img/details-3.png',
    rating: 3,
    price: 'Under $50',
    deliveryTime: '1 Week',
    availability: 'Coming Soon',
  },
  {
    id: 4,
    title: 'Introduction to Computer Science',
    description: 'Fundamentals of computer science and programming.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 5,
    title: 'Data Structures and Algorithms',
    description: 'Learn essential data structures and algorithms.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 6,
    title: 'Operating Systems Basics',
    description: 'Understand the basics of operating systems.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 7,
    title: 'Database Management Systems',
    description: 'Introduction to databases and SQL.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 8,
    title: 'Computer Networks',
    description: 'Learn about network protocols and architecture.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 9,
    title: 'Software Engineering Principles',
    description: 'Best practices in software development.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 10,
    title: 'Artificial Intelligence Basics',
    description: 'Introduction to AI concepts and techniques.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 11,
    title: 'Machine Learning Fundamentals',
    description: 'Learn the basics of machine learning algorithms.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 12,
    title: 'Web Development with JavaScript',
    description: 'Build dynamic websites using JavaScript.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 13,
    title: 'Mobile App Development',
    description: 'Create mobile apps for Android and iOS.',
    thumbnail: 'assets/img/details-1.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '4 Weeks',
    availability: 'Available Now',
  },
  {
    id: 14,
    title: 'Cybersecurity Essentials',
    description: 'Learn the fundamentals of cybersecurity.',
    thumbnail: 'assets/img/details-2.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 15,
    title: 'Cloud Computing Basics',
    description: 'Introduction to cloud services and architecture.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 16,
    title: 'Big Data Analytics',
    description: 'Learn to analyze large datasets effectively.',
    thumbnail: 'assets/img/details-1.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 17,
    title: 'Programming in Python',
    description: 'Learn Python programming from scratch.',
    thumbnail: 'assets/img/details-2.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 18,
    title: 'Data Science Introduction',
    description: 'Basics of data science and analysis.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 19,
    title: 'Computer Graphics',
    description: 'Learn the fundamentals of computer graphics.',
    thumbnail: 'assets/img/details-1.png',
    rating: 3,
    price: 'Under $50',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 20,
    title: 'Parallel Computing',
    description: 'Introduction to parallel and distributed computing.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',              
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 21,
    title: 'Software Testing',
    description: 'Learn software testing methodologies.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 22,
    title: 'Human-Computer Interaction',
    description: 'Study the design of user interfaces.',
    thumbnail: 'assets/img/details-1.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 23,
    title: 'Compiler Design',
    description: 'Learn the principles of compiler construction.',
    thumbnail: 'assets/img/details-2.png',
    rating: 3,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 24,
    title: 'Theory of Computation',
    description: 'Explore automata theory and formal languages.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 25,
    title: 'Computer Architecture',
    description: 'Understand the design of computer hardware.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 26,
    title: 'Network Security',
    description: 'Learn about securing computer networks.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 27,
    title: 'Distributed Systems',
    description: 'Study distributed computing systems and protocols.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 28,
    title: 'Mobile Computing',
    description: 'Learn about mobile computing technologies.',
    thumbnail: 'assets/img/details-1.png',
    rating: 3,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 29,
    title: 'Cloud Security',
    description: 'Understand security in cloud environments.',
    thumbnail: 'assets/img/details-2.png',
    rating: 5,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 30,
    title: 'Natural Language Processing',
    description: 'Introduction to NLP techniques and applications.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 31,
    title: 'Computer Vision',
    description: 'Learn about image processing and computer vision.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 32,
    title: 'Robotics Fundamentals',
    description: 'Basics of robotics and automation.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 33,
    title: 'Embedded Systems',
    description: 'Introduction to embedded system design.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 34,
    title: 'Blockchain Basics',
    description: 'Learn the fundamentals of blockchain technology.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 35,
    title: 'Quantum Computing',
    description: 'Introduction to quantum computing concepts.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '4 Weeks',
    availability: 'Available Now',
  },
  {
    id: 36,
    title: 'Javascript for Beginners',
    description: 'Learn about big data tools and platforms.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 3,
    title: 'Core JavaScript',
    description: 'Build dynamic websites using JavaScript.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 38,
    title: 'Advanced JavaScript',
    description: 'Build dynamic websites using JavaScript.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 39,
    title: 'Java Professinal Course',
    description: 'Build dynamic websites using JavaScript.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },  
];

export default sampleCourses;
