const sampleCourses = [
  {
    id: 1,
    title: 'React for Beginners',
    description: 'Learn the basics of React and build dynamic web apps.',
    about: 'This course covers React fundamentals, component-based architecture, hooks, and state management to build interactive web applications.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Day',
    availability: 'Available Now',
    recommended: true,
  },
  {
    id: 2,
    title: 'Advanced CSS Techniques',
    description: 'Master CSS for modern responsive design.',
    about: 'Explore advanced CSS concepts including flexbox, grid, animations, and responsive design techniques to create visually appealing websites.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Days',
    availability: 'Available Now',
    topRated: true,
  },
  {
    id: 3,
    title: 'Digital Marketing 101',
    description: 'Introduction to digital marketing strategies.',
    about: 'Learn the basics of digital marketing including SEO, social media marketing, email campaigns, and analytics to grow your online presence.',
    thumbnail: 'assets/img/details-3.png',
    rating: 3,
    price: 'Under $50',
    deliveryTime: '1 Week',
    availability: 'Coming Soon',
  },
  {
    id: 4,
    title: 'Introduction to Computer Science',
    description: 'Fundamentals of computer science and programming.',
    about: 'Understand core computer science principles, algorithms, data structures, and programming basics to build a strong foundation.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 5,
    title: 'Data Structures and Algorithms',
    description: 'Learn essential data structures and algorithms.',
    about: 'Master key data structures and algorithms to improve problem-solving skills and prepare for technical interviews.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 6,
    title: 'Operating Systems Basics',
    description: 'Understand the basics of operating systems.',
    about: 'Explore operating system concepts such as processes, memory management, file systems, and concurrency.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 7,
    title: 'Database Management Systems',
    description: 'Introduction to databases and SQL.',
    about: 'Learn database design, SQL queries, normalization, and transactions to manage data effectively.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 8,
    title: 'Computer Networks',
    description: 'Learn about network protocols and architecture.',
    about: 'Understand networking fundamentals, protocols, models, and security to build and manage networks.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 9,
    title: 'Software Engineering Principles',
    description: 'Best practices in software development.',
    about: 'Study software development methodologies, design patterns, testing, and maintenance for quality software.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 10,
    title: 'Artificial Intelligence Basics',
    description: 'Introduction to AI concepts and techniques.',
    about: 'Explore AI fundamentals, machine learning, neural networks, and applications in various fields.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 11,
    title: 'Machine Learning Fundamentals',
    description: 'Learn the basics of machine learning algorithms.',
    about: 'Understand supervised and unsupervised learning, model evaluation, and practical ML applications.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 12,
    title: 'Web Development with JavaScript',
    description: 'Build dynamic websites using JavaScript.',
    about: 'Learn JavaScript programming, DOM manipulation, event handling, and modern frameworks.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 13,
    title: 'Mobile App Development',
    description: 'Create mobile apps for Android and iOS.',
    about: 'Develop mobile applications using native and cross-platform tools with best practices.',
    thumbnail: 'assets/img/details-1.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '4 Weeks',
    availability: 'Available Now',
  },
  {
    id: 14,
    title: 'Cybersecurity Essentials',
    description: 'Learn the fundamentals of cybersecurity.',
    about: 'Understand security principles, threats, cryptography, and defense mechanisms.',
    thumbnail: 'assets/img/details-2.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 15,
    title: 'Cloud Computing Basics',
    description: 'Introduction to cloud services and architecture.',
    about: 'Explore cloud models, services, deployment, and management in modern IT environments.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 16,
    title: 'Big Data Analytics',
    description: 'Learn to analyze large datasets effectively.',
    about: 'Study big data tools, processing techniques, and analytics for business insights.',
    thumbnail: 'assets/img/details-1.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 17,
    title: 'Programming in Python',
    description: 'Learn Python programming from scratch.',
    about: 'Master Python syntax, libraries, and applications in data science and web development.',
    thumbnail: 'assets/img/details-2.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 18,
    title: 'Data Science Introduction',
    description: 'Basics of data science and analysis.',
    about: 'Understand data analysis, visualization, statistics, and machine learning basics.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 19,
    title: 'Computer Graphics',
    description: 'Learn the fundamentals of computer graphics.',
    about: 'Explore graphics programming, rendering techniques, and visualization.',
    thumbnail: 'assets/img/details-1.png',
    rating: 3,
    price: 'Under $50',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 20,
    title: 'Parallel Computing',
    description: 'Introduction to parallel and distributed computing.',
    about: 'Study parallel algorithms, architectures, and distributed systems concepts.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 21,
    title: 'Software Testing',
    description: 'Learn software testing methodologies.',
    about: 'Understand testing types, test planning, automation, and quality assurance.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 22,
    title: 'Human-Computer Interaction',
    description: 'Study the design of user interfaces.',
    about: 'Learn usability principles, interaction design, and user experience evaluation.',
    thumbnail: 'assets/img/details-1.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 23,
    title: 'Compiler Design',
    description: 'Learn the principles of compiler construction.',
    about: 'Explore lexical analysis, parsing, code generation, and optimization techniques.',
    thumbnail: 'assets/img/details-2.png',
    rating: 3,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 24,
    title: 'Theory of Computation',
    description: 'Explore automata theory and formal languages.',
    about: 'Study automata, formal languages, computability, and complexity theory.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 25,
    title: 'Computer Architecture',
    description: 'Understand the design of computer hardware.',
    about: 'Learn CPU design, memory hierarchy, instruction sets, and performance optimization.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 26,
    title: 'Network Security',
    description: 'Learn about securing computer networks.',
    about: 'Understand network threats, firewalls, VPNs, and security protocols.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 27,
    title: 'Distributed Systems',
    description: 'Study distributed computing systems and protocols.',
    about: 'Explore distributed algorithms, consensus, fault tolerance, and system design.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 28,
    title: 'Mobile Computing',
    description: 'Learn about mobile computing technologies.',
    about: 'Understand mobile platforms, wireless communication, and app development.',
    thumbnail: 'assets/img/details-1.png',
    rating: 3,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 29,
    title: 'Cloud Security',
    description: 'Understand security in cloud environments.',
    about: 'Learn cloud security principles, compliance, and best practices.',
    thumbnail: 'assets/img/details-2.png',
    rating: 5,
    price: '$50 to $100',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 30,
    title: 'Natural Language Processing',
    description: 'Introduction to NLP techniques and applications.',
    about: 'Explore text processing, machine learning, and language models.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 31,
    title: 'Computer Vision',
    description: 'Learn about image processing and computer vision.',
    about: 'Study image analysis, feature extraction, and computer vision applications.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 32,
    title: 'Robotics Fundamentals',
    description: 'Basics of robotics and automation.',
    about: 'Learn robot kinematics, sensors, control systems, and automation techniques.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 33,
    title: 'Embedded Systems',
    description: 'Introduction to embedded system design.',
    about: 'Explore microcontrollers, real-time systems, and embedded programming.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '2 Weeks',
    availability: 'Available Now',
  },
  {
    id: 34,
    title: 'Blockchain Basics',
    description: 'Learn the fundamentals of blockchain technology.',
    about: 'Understand blockchain architecture, consensus algorithms, and smart contracts.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 35,
    title: 'Quantum Computing',
    description: 'Introduction to quantum computing concepts.',
    about: 'Explore quantum algorithms, qubits, and quantum hardware.',
    thumbnail: 'assets/img/details-2.png',
    rating: 4,
    price: '$50 to $100',
    deliveryTime: '4 Weeks',
    availability: 'Available Now',
  },
  {
    id: 36,
    title: 'Javascript for Beginners',
    description: 'Learn about big data tools and platforms.',
    about: 'Introduction to JavaScript programming, syntax, and web development basics.',
    thumbnail: 'assets/img/details-3.png',
    rating: 4,
    price: 'Under $50',
    deliveryTime: '3 Weeks',
    availability: 'Available Now',
  },
  {
    id: 37,
    title: 'Core JavaScript',
    description: 'Build dynamic websites using JavaScript.',
    about: 'Master JavaScript fundamentals, DOM manipulation, and event handling.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 38,
    title: 'Advanced JavaScript',
    description: 'Build dynamic websites using JavaScript.',
    about: 'Learn advanced JavaScript concepts, ES6 features, and modern frameworks.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 39,
    title: 'Java Professinal Course',
    description: 'Build dynamic websites using JavaScript.',
    about: 'This course is based on the Udemy course "Java - The Complete Java Developer Course". It covers Java fundamentals, object-oriented programming, data structures, algorithms, and more. The course is designed for beginners and intermediate learners who want to master Java development.',
    thumbnail: 'assets/img/details-3.png',
    rating: 5,
    price: 'Free',
    deliveryTime: '1 Week',
    availability: 'Available Now',
  },
  {
    id: 40,
    title: 'Learn JAVA Programming - Beginner to Master',
    description: 'Deep Dive in Core Java programming -Standard Edition. A Practical approach to learn Java. Become a Java Expert',
    about: 'This course provides a comprehensive guide to core Java programming, covering fundamental concepts, practical applications, and expert techniques to master Java development.',
    thumbnail: 'assets/img/details-1.png',
    rating: 5,
    price: 'Free',
    deliveryTime: 'N/A',
    availability: 'Available Now',
  },
];

export default sampleCourses;
